# -*- coding: utf-8 -*-
"""YK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3BKSIXiPm_mvfm3s2shDXIItqvGrlz_
"""

import pandas as pd

df = pd.read_csv("retail_sales.csv")
df.head()

df.info()
df.shape
df.columns

df.isnull().sum()
df.dropna(inplace=True)

df['Date'] = pd.to_datetime(df['Date'])

df.drop_duplicates(inplace=True)

df.describe()

df.columns

df['Date'] = pd.to_datetime(df['Date'])

monthly_sales = df.groupby(df['Date'].dt.month)['Total Amount'].sum()
monthly_sales

monthly_sales.plot(kind='line', title='Monthly Sales Trend')

df.groupby('Product Category')['Total Amount'].sum().sort_values(ascending=False)

import seaborn as sns
import matplotlib.pyplot as plt

sns.barplot(x='Product Category', y='Total Amount', data=df)
plt.show()

